name: "🐞 Bug Report"
description: "File a bug or issue for Pip Reroller"
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
assignees: []

body:
  - type: input
    attributes:
      label: "Bug Description"
      description: "Describe the bug or issue you encountered in detail"
      placeholder: "E.g. The reroller crashes after the 5th roll."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the bug"
      placeholder: |
        1. Open Pip Reroller
        2. Select the reroll option
        3. Wait until the 5th roll
        4. Observe crash
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected Behavior"
      description: "What you expected to happen"
      placeholder: "Reroller continues without crashing"
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Actual Behavior"
      description: "What actually happened"
      placeholder: "The app closes unexpectedly."
    validations:
      required: false

  - type: textarea
    attributes:
      label: "Environment"
      description: |
        Please include relevant specs like:
        - OS: Windows 10 21H2
        - CPU/GPU: Intel i7, NVIDIA RTX 3080
        - Average Ping: 45 ms
        - Monitor Refresh Rate: 144 Hz
        - Average FPS: 120
      placeholder: |
        - OS:
        - CPU/GPU:
        - Average Ping:
        - Monitor Refresh Rate:
        - Average FPS:
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional Information"
      description: |
        Anything else that might help us debug the issue: logs, screenshots, error messages, etc.
    validations:
      required: false
