name: Build and Release PipReroller

on:
  workflow_dispatch:
    inputs:
      output_filename:
        description: 'Output exe filename'
        required: true
        default: 'PipReroller.exe'
      tag_name:
        description: 'Git tag to create/release'
        required: true
        default: 'v1.0.0'
      release_name:
        description: 'Release title'
        required: true
        default: 'PipReroller Release'
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        default: 'false'
        type: boolean

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Build executable with Nuitka
      run: |
        nuitka main.pyw --standalone --onefile --windows-console-mode=disable --enable-plugin=tk-inter --enable-plugin=pylint-warnings --include-package=ahk --include-package=jinja2 --include-package=markupsafe --include-package=cv2 --include-package=pynput --include-package=win32gui --include-package=win32ui --include-package=win32con --include-package=six --windows-icon-from-ico=assets/favicon.ico --output-filename=${{ github.event.inputs.output_filename }} --output-dir=build --assume-yes-for-downloads

    - name: Compute SHA256 checksum
      run: |
        certutil -hashfile build\${{ github.event.inputs.output_filename }} SHA256 > build\${{ github.event.inputs.output_filename }}.sha256.txt

    - name: Create or update GitHub release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.release_name }}
        prerelease: ${{ github.event.inputs.prerelease }}

    - name: Upload exe to release
      uses: softprops/action-gh-release@v1
      with:
        files: build/${{ github.event.inputs.output_filename }}

    - name: Upload checksum to release
      uses: softprops/action-gh-release@v1
      with:
        files: build/${{ github.event.inputs.output_filename }}.sha256.txt

    - name: Output info
      run: |
        echo "Executable URL: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag_name }}/${{ github.event.inputs.output_filename }}"
        echo "Build logs: $GITHUB_SERVER_URL/${{ github.repository }}/actions/runs/${{ github.run_id }}"
