name: Build and Release PipReroller

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Git tag to create/release'
        required: true
        default: 'v1.0.0'
      prerelease:
        description: 'Is this a prerelease?'
        required: true
        default: 'false'
        type: boolean

jobs:
  build_and_release:
    runs-on: windows-latest

    env:
      OUTPUT_NAME: PipReroller${{ github.event.inputs.tag_name }}.exe
      RELEASE_NAME: PipReroller Release ${{ github.event.inputs.tag_name }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Build executable with Nuitka
      run: |
        nuitka main.pyw --standalone --onefile --windows-console-mode=disable `
          --enable-plugin=tk-inter `
          --enable-plugin=pylint-warnings `
          --include-package=ahk `
          --include-package=jinja2 `
          --include-package=markupsafe `
          --include-package=cv2 `
          --include-package=pynput `
          --include-package=win32gui `
          --include-package=win32ui `
          --include-package=win32con `
          --include-package=six `
          --windows-icon-from-ico=assets/favicon.ico `
          --output-filename="${{ env.OUTPUT_NAME }}" `
          --output-dir=build `
          --assume-yes-for-downloads

    - name: List build directory contents (for debugging)
      run: dir build

    - name: Compute SHA256 checksum
      shell: pwsh
      run: |
        $hash = (certutil -hashfile "build/${{ env.OUTPUT_NAME }}" SHA256)[1].Trim()
        "$hash  ${{ env.OUTPUT_NAME }}" | Out-File -Encoding ascii -NoNewline "build/${{ env.OUTPUT_NAME }}.sha256.txt"

    - name: Create or update GitHub release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ env.RELEASE_NAME }}
        prerelease: ${{ github.event.inputs.prerelease }}

    - name: Upload exe to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        files: build/${{ env.OUTPUT_NAME }}

    - name: Upload checksum to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.tag_name }}
        files: build/${{ env.OUTPUT_NAME }}.sha256.txt

    - name: Output info
      run: |
        echo "Executable URL: https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag_name }}/${{ env.OUTPUT_NAME }}"
        echo "Build logs: $GITHUB_SERVER_URL/${{ github.repository }}/actions/runs/${{ github.run_id }}"
